version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db: 
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=laundry-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - laundry-pgdata:/var/lib/postgresql/data
    
volumes:
  laundry-pgdata: 
    name: "laundry-pgdata"
